apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 855758428609.dkr.ecr.ap-south-1.amazonaws.com/b12:3adbc39ebd762f32f98869b32fd28829dd5ac1ca
          ports:
            - containerPort: 3000
