apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 855758428609.dkr.ecr.ap-south-1.amazonaws.com/b12:78b2656395d44128ccfe14d7167c8470133d02f7
          ports:
            - containerPort: 3000
